definitions:
  model.AmqpMessage:
    properties:
      created:
        type: integer
      data: {}
      message_id:
        type: string
      operation:
        type: string
      source:
        type: string
    required:
    - created
    - data
    - message_id
    - operation
    - source
    type: object
  model.Message:
    properties:
      created_at:
        type: string
      dead:
        type: boolean
      id:
        type: integer
      message:
        $ref: '#/definitions/model.AmqpMessage'
      retried:
        type: boolean
      routing:
        type: string
    type: object
  v1.errorResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  v1.messageCreateRequestDto:
    properties:
      message:
        $ref: '#/definitions/model.AmqpMessage'
      routing:
        type: string
    required:
    - message
    - routing
    type: object
  v1.messageCreateResponseDto:
    properties:
      id:
        type: integer
    type: object
  v1.messageResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Message'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/v1/messages:
    get:
      consumes:
      - application/json
      description: Message
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - in: query
        name: routing
        type: string
      - in: query
        name: sort_type
        type: string
      - in: query
        name: source
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.messageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorResponse'
      summary: Список элементов "Сообщение"
      tags:
      - Messages / Сообщения
    post:
      consumes:
      - application/json
      description: Message
      parameters:
      - description: messages
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.messageCreateRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.messageCreateResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorResponse'
      summary: Создание элемента "Сообщение"
      tags:
      - Messages / Сообщения
  /api/v1/messages/{id}:
    get:
      consumes:
      - application/json
      description: Сообщение
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorResponse'
      summary: Получение элемента "Сообщение" по id
      tags:
      - Messages / Сообщения
swagger: "2.0"
